language: 
  - java

jdk:
  - oraclejdk8

install:
  - mvn clean package

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" ;

      docker build -t robsonbittencourt/payara-micro-test:latest . ;
    
      docker push docker.io/robsonbittencourt/payara-micro-test:latest ;
    fi

cache:
  directories:
    - $HOME/.m2 